name: Auto Build Packages

on:
  push:
    branches:
      - main
    # paths:
    #   - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.sender.login != 'GitHub Action'

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version: '^1.20.0'

    - name: Check builds
      shell: bash
      run: |
        echo "$(go version)"
        make build-all

  tag:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        package: [even, odd]
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
        tag_prefix: packages/${{ matrix.package }}/v

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}

  sync-and-commit:
    needs: tag
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get latest tag
      id: latest_tag
      shell: bash
      run: |
        echo "LATEST_TAG=$(git describe --abbrev=0 --tags --match="$PREFIX_MATCH/*" 2>&1 | awk -F'/' '{print $NF}')" >> $GITHUB_ENV

    - name: Update package dependencies
      id: update_package_dependencies
      shell: bash
      run: |
        cd packages/
        for folder in */; do
          package=${folder%/}
          make replace-deps package=${{ matrix.package }} version=$LATEST_TAG
        done

    - name: Commit modified dependencies
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Upgrade packages" -a || exit 0

    - name: Push changes
      run: |
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
