name: Auto Build Packages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.sender.login != 'GitHub Action'

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version: '^1.20.0'

    - name: Check builds
      shell: bash
      run: |
        echo "$(go version)"
        make build-all
